### ISSUE TITLE
world.output_role.db = None leads to attribute error in DRL examples

### ISSUE THREAD

**Issue by AndreasEppler** [assume-framework/assume#512] opened 2024-12-09 10:17 UTC
Issue found by @mthede 
When running 04_reinforcement_learning_algorithm_example.ipynb or 09_example_Sim_and_xRL.ipynb, the following issue emerges:
![image](https://github.com/user-attachments/assets/ca775f09-6c32-4f1c-9a94-c00ecc743529)
The issue occurs when calling world.output_role.delete_simular_runs() or world.output_role.get_sum_reward()
This appears to be due to a recent change in the WriteOutput class, where db is now initialized as None.
![image](https://github.com/user-attachments/assets/dbca055a-c1d3-4865-a263-6d879f5a23c7)
Adding the if-clause
```
if world.output_role.db is not None:
        world.output_role.delete_similar_runs()
``` 
to the run_learning function has been successfully found to be a quick fix for the issue that obviously does not address the problem at its root.

**Comment by maurerle** [comment] 2024-12-09 12:02
Hi, I doubt that this error comes from an uninitialized db_uri - if you do not provide a DB_URI, there should not be any output_role - not a `has no attribute 'delete_similar_runs'`.

Did you check if this occurs on main as well?
I have the feeling, that the two mentioned examples are not working that well.
I don't have any folder `inputs/tutorial_09` locally for example..?

I fixed some issues for the output role in the attached PR though.

**Comment by AndreasEppler** [comment] 2024-12-09 13:52
Hi, thanks for looking into it.
The `inputs/tutorial_09` folder seems to be created and used in `10_DSU_and_flexibility.ipynb`.
`09_example_Sim_and_xRL.ipynb` uses the `inputs/tutorial_08` folder created by executing `08_market_zone_coupling.ipynb`. The execution of notebook 08 is done at the beginning of notebook 09, however, the line was currently only executed in google colab. I'll fix this and create a PR.

**Comment by maurerle** [comment] 2024-12-09 15:15
I think I understand now:

I renamed this function in https://github.com/assume-framework/assume/commit/d21a4e566d2c7c6c65555d6b76ae14c64a2e8683

So one must use the matching assume version from main today.
Or use the new release which will be available soon.

**Comment by AndreasEppler** [comment] 2024-12-09 15:22
I don't think the renaming of the function is what is causing the issue, as I have today's main assume version. It seems to be due to self.db being initialized as None instead of db_engine. Does thismake sense?

**Comment by maurerle** [comment] 2024-12-09 15:31
There is no way an object of type `WriteOutput` would not have the method `delete_similar_runs` with current main..

Maybe try to run `python -m pip uninstall assume-framework` and then run `pip install -e . ` or something? wrong env? wrong python interpreter running (`which python` or `where python` on windows)? different python interpreter when running python vs python3?

**Comment by mthede** [comment] 2024-12-09 15:45
Initially, I found this issue when I was working with the Grafana training progress dashboard. When running the same example (small_learning_1) multiple times, the data from the last simulation is not deleted. With progressing episodes, it will only be overwritten. 

I pulled your latest commits, looked into it again and it still doesn't succesfully delete the previous similar run. 
In debug mode I saw that the self.db_uri is given, however self.db will be accessed and is `None'
![grafik](https://github.com/user-attachments/assets/355c447d-16de-47f8-b399-610e2d575253)

**Comment by AndreasEppler** [comment] 2024-12-09 15:46
![image](https://github.com/user-attachments/assets/d353b566-fde8-40b5-b85b-5ef0d60b28c1)
Yes, it's also happening on colab, reinstalling assume doeas not change anything.

**Comment by maurerle** [comment] 2024-12-09 16:22
Sorry, I can't reproduce this. Maybe you can provide a minimal example for this?

I can only imagine that you are using an old release... try running:
`!pip install https://github.com/assume-framework/assume/archive/refs/heads/main.zip` or create a fresh env

**Comment by maurerle** [comment] 2024-12-10 07:55
Maybe you can check if you can still reproduce this, now that https://pypi.org/project/assume-framework/ is released

**Comment by mthede** [comment] 2024-12-10 08:56
The new version didn't change the behavior for me.

**Comment by mthede** [comment] 2024-12-10 09:10
I'm not sure if a minimal example helps if it's caused by some version/environment error... but I'll try to explain/how it by going through the code. 

Try examples.py with `small_learning_1` and add `episode=0` in `load_scenario_folder()`:
![grafik](https://github.com/user-attachments/assets/2f3426e9-07c2-4a5b-b9d3-a1f1dd19f34c)

[BTW: the default for episode/eval_episode is set to 1 in `load_scenario_folder()` , although docs say "Defaults to 0."]

The output role will then initialize `self.db = None` in line 83 and in line 98 call `delete_similar_runs()`.
![grafik](https://github.com/user-attachments/assets/9f23072d-474a-4dbe-95c8-a2706b62a57a)

Now, an Exception is caught because self.db is still None and self.db.begin() is not possible.
![grafik](https://github.com/user-attachments/assets/97f6c71c-f829-4704-9adb-ba43b7758323)

Does that help?

**Comment by mthede** [comment] 2024-12-10 09:58
The behavior seems to be the same with the new release. I restarted docker (had to change the path for volumes again from  ` ./assume-db:/home/postgres/pgdata` to ` ./assume-db:/home/postgres/data` for the timescaledev image) and checked that I'm working with the latest release.

I'm not sure if a minimal example helps if it's caused by some version/environment error... but I'll try to explain/how it by going through the code. 

Try examples.py with `small_learning_1` and add `episode=0` in `load_scenario_folder()`:
![grafik](https://github.com/user-attachments/assets/a0210206-668e-4bf9-af61-9f83cbf3097c)

[BTW: the default for episode/eval_episode is set to 1 in `load_scenario_folder()` , although docs say "Defaults to 0."]

The output role will then initialize `self.db = None` in line 83 and in line 98 call `delete_similar_runs()`.
![grafik](https://github.com/user-attachments/assets/9f23072d-474a-4dbe-95c8-a2706b62a57a)

Now, an Exception is caught because self.db is still None and self.db.begin() is not possible.
![grafik](https://github.com/user-attachments/assets/97f6c71c-f829-4704-9adb-ba43b7758323)

Does that help?

**Comment by maurerle** [comment] 2024-12-10 11:31
@mthede
I still can't reproduce this issue.
Are you sure the error message did not change since the release?

Maybe someone else can try to reproduce and fix this.

**Comment by mthede** [comment] 2024-12-10 11:52
With the described example above, I don't get an error message either. I just noticed the unexpected behavior that similar runs were not deleted in the database. But that was fixed with your most recent PR, I've already tried it.

The errors described by Andreas from the notebooks seem to be resolved with the new release. (Maybe @AndreasEppler can confirm this again, but he told me that example 9 fully ran without any problems.)

So most likely we were talking about two different issues? Both seem to be fixed :) thanks!

**Closed** 2024-12-12 09:52 UTC
